### ISSUE TITLE
KW Get Attribute Names dose not always return a list

### ISSUE THREAD

**Issue by mawentao119** [MarketSquare/robotframework-browser#2890] opened 2023-06-25 05:04 UTC
**Describe the bug**
If the element just has one attribute('class' for example) , the KW Get Attribute Names does not returns a list but a string ('class').

**The CODE**

    @{续期attr}=    Get Attribute Names    ${buttons}[0]
    @{退回attr}=    Get Attribute Names    ${buttons}[1]
    @{降级attr}=    Get Attribute Names    ${buttons}[2]

    IF    "${权限input}" == "只读"
        List Should Not Contain Value    ${续期attr}    disabled
        List Should Not Contain Value    ${退回attr}    disabled
        List Should Contain Value    ${降级attr}    disabled
    END

**The LOG**
${续期attr} = class
${退回attr} = class
${降级attr} = ['class', 'disabled', 'style']

**Comment by aaltat** [comment] 2023-06-25 12:41
Good catch, it would be bets to always return a list. 

@allcontributors please add @mawentao119 for bugs

**Comment by aaltat** [comment] 2023-06-25 15:32
I can not reproduce the issue, [Get Attribute Names](https://marketsquare.github.io/robotframework-browser/Browser.html#Get%20Attribute%20Names) returns always a list. I have vague recollection that this was not always a case and it was fixed in some release. Are you perhaps using an older versions of Browser library. 

This was not actually tested and I did enhance our acceptance tests https://github.com/MarketSquare/robotframework-browser/pull/2892

**Comment by aaltat** [comment] 2023-06-25 15:43
Because keyword returns a list, I am going to close the issue. But if you would have an example where this is not true by using the latest version of the library, please provide more details and we can reconsider opening the issue.

**Closed by aaltat** 2023-06-25 15:43 UTC

**Comment by mawentao119** [comment] 2023-06-26 02:30
I will check the library version. And then test again.

Tatu Aalto ***@***.***> 于2023年6月25日周日 23:43写道：

**Comment by aaltat** [comment] 2023-06-27 06:14
If you can reproduce the problem, can we see the html element which returns the names and how you are calling the keyword?
