### ISSUE TITLE
Support beforeunload dialogs

### ISSUE THREAD

**Issue by Reddriver** [MarketSquare/robotframework-browser#2098] opened 2022-06-09 08:29 UTC
@aaltat We discussed on Slack [https://robotframework.slack.com/archives/C015KB1QSDN/p1652876531579199](https://robotframework.slack.com/archives/C015KB1QSDN/p1652876531579199) my problem with beforeunload dialogs. This type of dialog is not visible in Browser library. In Python Playwright dialog is visible.

```
python code:
from textwrap import fill
from playwright.sync_api import sync_playwright

def handle_dialog(dialog):
    # dialog.dismiss()
    dialog.accept()

def run(playwright):
    chromium = playwright.chromium
    browser = chromium.launch(executable_path="C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",headless=False)
    page = browser.new_page()
    page.goto("https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onbeforeunload")
    page.locator('text=Přijmout').click()
    page.on("dialog", handle_dialog)
    page.goto('https://seznam.cz/')
    browser.close()

with sync_playwright() as playwright:
    run(playwright)
```
Let me know, I will test new feature.

**Comment by aaltat** [comment] 2022-06-10 18:03
@allcontributors please add @Reddriver for ideas.

**Comment by aaltat** [comment] 2023-05-28 17:41
Interesting, I can reproduce the issue, the dialogue is automatically accepted. But in our code, we do not do call `page.on("dialog", ...` As far I can see from the code.

**Comment by aaltat** [comment] 2023-05-28 17:48
Ah not I found it, this comes Playwright has automatic dismiss on dialogues: https://playwright.dev/docs/api/class-dialog unless we set the `page.on("dialog", ...`, example by calling [Handle Future Dialogs](https://marketsquare.github.io/robotframework-browser/Browser.html#Handle%20Future%20Dialogs) keyword. Because this is done automatically by Playwright, only way for user to change the behavior is call the alert handling keyword from the library. 

Because this is done by PW, I am going to close this issue.

**Closed by aaltat** 2023-05-28 17:48 UTC
Labels: enhancement, priority: high
