### ISSUE TITLE
Selecting an option without explicit value fails

### ISSUE THREAD

**Issue by laurihelkkula** [MarketSquare/robotframework-browser#1780] opened 2022-02-17 23:38 UTC
**Describe the bug**
Selecting an option without explicit value fails

**To Reproduce**

Given a select with options that don't have value set:
``` html
<select>
 <option>Option 1</option>
 <option>Option 2</option>
</select>
```

Run in a test:
```robot
*** Settings ***
Library           Browser

*** Keywords ***
Select Option 2
  New Page  ${theUrl}
  #decrease timeout for faster execution
  Set Browser Timeout  100ms
  Select Options By  select  text  Option 2
```

When the test is run, the correct option is selected, but then an error is generated:
```
[ FAIL ] TimeoutError: locator.elementHandle: Timeout 100ms exceeded.
=========================== logs ===========================
waiting for selector "select >> option[value="Option 2"]"
============================================================
```

**Expected behavior**
No errors

**Screenshots**
Not necessary, I assume

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome, firefox
 - Version: robotframework-browser 11.4.0

**Additional context**
I think the problem is this code that assumes all options have a value:
https://github.com/MarketSquare/robotframework-browser/blob/427e5050bbcf77e9d026cf313219c917b14e6440/node/playwright-wrapper/interaction.ts#L41

Workaround: use Run Keyword And Expect Error
```robot
  Run Keyword And Expect Error  *locator.elementHandle*option[value*
  ...  Select Options By  select  text  Option 2
```

**Comment by aaltat** [comment] 2022-02-18 16:39
@allcontributors please add @laurihelkkula for bugs.

**Comment by aaltat** [comment] 2022-02-19 20:33
This is actually duplicate of #1622 Therefore closing.

**Closed by aaltat** 2022-02-19 20:33 UTC
Labels: bug, priority: high
