### ISSUE TITLE
Importing Browser fails with docker image 17.5

### ISSUE THREAD

**Issue by mika-b** [MarketSquare/robotframework-browser#3104] opened 2023-09-25 09:43 UTC
**Describe the bug**
With Docker image 17.5 (current 'latest') Browser library can not be imported. 17.4 works just fine. 

**To Reproduce**
1) docker pull marketsquare/robotframework-browser:17.4
2) docker pull marketsquare/robotframework-browser:17.5
3) docker run --rm -v $(pwd)/atest/test/:/test --ipc=host --user pwuser --security-opt seccomp=seccomp_profile.json marketsquare/robotframework-browser:17.5 bash -c "robot --outputdir /test/output /test/00_Clean_Output_Dir/01_initial_import.robot"

With 17.5 importing Browser fails
```
[ ERROR ] Error in file '/test/00_Clean_Output_Dir/01_initial_import.robot' on line 2: Initializing library 'Browser' with arguments [ retry_assertions_for=0:00:02 ] failed: Could not find node dependencies in installation directory `/home/pwuser/.local/lib/python3.8/site-packages/Browser/wrapper.` Run `rfbrowser init` to install the dependencies.
Traceback (most recent call last):
  File "/home/pwuser/.local/lib/python3.8/site-packages/Browser/browser.py", line 798, in __init__
    self.playwright = Playwright(
  File "/home/pwuser/.local/lib/python3.8/site-packages/Browser/playwright.py", line 51, in __init__
    self.ensure_node_dependencies()
  File "/home/pwuser/.local/lib/python3.8/site-packages/Browser/playwright.py", line 81, in ensure_node_dependencies
    raise RuntimeError(
RuntimeError: Could not find node dependencies in installation directory `/home/pwuser/.local/lib/python3.8/site-packages/Browser/wrapper.` Run `rfbrowser init` to install the dependencies.
==============================================================================
01 Initial Import                                                             
==============================================================================
...
```

**Expected behavior**
No traceback with 17.4
```
robotframework-browser$ docker run --rm -v $(pwd)/atest/test/:/test --ipc=host --user pwuser --security-opt seccomp=seccomp_profile.json marketsquare/robotframework-browser:17.4 bash -c "robot --outputdir /test/output /test/00_Clean_Output_Dir/01_initial_import.robot"
==============================================================================
01 Initial Import                                                             
==============================================================================
... FAILS BUT OUT OF SCOPE FOR THIS ONE
```

**Comment by aaltat** [comment] 2023-09-25 10:01
Duplicate of https://github.com/MarketSquare/robotframework-browser/issues/3100 closing. Will try to push release out later today

**Closed by aaltat** 2023-09-25 10:01 UTC
