### ISSUE TITLE
Trace viewer doesn't show formatted screen on main screen

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-browser#1096] opened 2021-06-22 17:30 UTC
**Describe the bug**
I took a first look at the show-trace option of rfbrowser. It has great potential.

After starting the show-trace I'm presented with a screen with 4 parts
1) top, containing timeline with formatted screenshots 
2) left, all clicks/fills go to executed during test
3) right, all resource and network activity

That's all great.

The problem is with the main screen, which should contain the FORMATTED screen at that point in time. Problem is that no formatting seems to take place. Everything is below each other: menu, several tables. forms etc. stylesheets etc and coloring is not applied. The rest of the show-trace app seems to work as expected

I can't share pictures of this unfortunately, but I was wondering if something can be done to get the main screen formatted. Now the point were a click is applied is screwed up (or doesn't point to the correct point).

This could be caused by local network restrictions, but I was under the impression that all resources to format the trace, were in the trace.zip

**To Reproduce**
every "rfbrowser show-trace F <file>

**Expected behavior**
I expected the main screen to look like: "https://www.youtube.com/watch?v=Zutt7N6VvcU"  when clicked on actions

**Screenshots**
The mainscreen, but no formatting of coloring on the web page
![image](https://user-images.githubusercontent.com/72747481/122972108-12420500-d390-11eb-9ee9-83c78a3b7460.png)

**Desktop (please complete the following information):**
 - robotframework 5.1.1
 - playwright 12.2

**Comment by emakaay** [comment] 2021-06-22 21:38
Perhaps this problem is already fixed with new version of playwright.....

https://github.com/microsoft/playwright/issues/6985#issuecomment-861400445.

But I don't have access to this @next release to check it

**Comment by aaltat** [comment] 2021-06-24 14:05
There tracing is based on Playwright and library servers only as thin wrapper on the top. If the UI opens, but is missing something, then it's a bug in the Playwright side, most likely. 

Could you share example that demonstrates the problem? Also could you share details about the OS you are using?

**Comment by emakaay** [comment] 2021-06-24 15:33
I already added an example.
The login pain should contain formatting.
Css coloring is missing. Also placement of elements is incorrect

When looking at dev console several errors are shown that css and js files can't be found(404). But I can't show you that(corporate issue)

**Comment by emakaay** [comment] 2021-06-24 15:34
Will retry when new version of playwright is available. I can't get the @next version of playwright(corporate issue)

**Comment by aaltat** [comment] 2021-06-28 07:26
There was a new release from PW side which has fixes on this subject: https://github.com/Microsoft/playwright/issues/7085

**Comment by emakaay** [comment] 2021-06-29 08:18
The new version did not solve the problem. I first tried with a trace zip
file from previous playwright version(1.12.2) which has the same
problem.... No formatting. Then I created a new zip with
playwright(1.12.3), and started the show trace command. No difference...
I'm sorry to say

**Comment by aaltat** [comment] 2021-06-29 21:03
I can not reproduce the problem. For me the trace viewer looks same as in Playwright docs: https://playwright.dev/docs/trace-viewer

The `rfbrowser show-trace` [command](https://github.com/MarketSquare/robotframework-browser/blob/master/Browser/entry.py#L92-L99) is pretty simple. You could add few `print()` to to display your environment details and run the same command from your shell. If the problem reproduces then the problem is in the playwright side and you need to report the issue to them.

**Comment by aaltat** [comment] 2021-07-08 06:50
Did you time to try it out manually from the command line?

**Comment by emakaay** [comment] 2021-07-10 17:46
Hello Tatu,

I didn't have time to check it manually from the commandline.
I'm waiting for the new release of playwright 1.12.4 or 1.13
Then I will check again

**Comment by aaltat** [comment] 2021-07-22 08:32
New pw release is out, could you retest,

**Comment by emakaay** [comment] 2021-07-22 16:09
Hello Tatu,
I retested.
It still is the same problem.

Currently little bit short on time. I don't know when I can move the issue
to the playwright issue list. But will do that as soon i have time.

Erik

**Comment by aaltat** [comment] 2021-07-25 22:37
I will close the issue because it looks like a PW side problem. If you feel differently, please tell why.

**Closed by aaltat** 2021-07-25 22:37 UTC

**Comment by emakaay** [comment] 2021-08-09 15:30
opened issue with playwright: https://github.com/microsoft/playwright/issues/8095

**Comment by emakaay** [comment] 2021-10-03 10:04
tested with robotframework 8.0.2 and playwright 15.1. It's getting better, but still not all problems are resolved
