### ISSUE TITLE
Catalog contains pages' title with None values

### ISSUE THREAD

**Issue by luchoagomezt** [MarketSquare/robotframework-browser#1867] opened 2022-03-16 14:12 UTC
**Describe the bug**
get_browser_catalog returns pages with None value for the "title"

**To Reproduce**
Snniped code from the test case, in the attachments:

    def test_open_and_close_first_popup(self):
        # Open first popup
        self.browser_lib.click('css=div[id="first_popup"]')

        # Close first popup
        self.browser_lib.switch_page("NEW")
        self.browser_lib.click('css=div[id="close"]')

        catalog = self.browser_lib.get_browser_catalog()
        pages = catalog[0]["contexts"][0]["pages"]
        for page in pages:
            assert page["title"] is not None

**Expected behavior**
The title must not be None

**Screenshots**
NA
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chromium

**Smartphone (please complete the following information):**
NA

**Additional context**
Test cases:
[test_catalog.py.txt](https://github.com/MarketSquare/robotframework-browser/files/8262812/test_catalog.py.txt)

HTML files:
[Popups.zip](https://github.com/MarketSquare/robotframework-browser/files/8262819/Popups.zip)

**Comment by aaltat** [comment] 2022-03-17 19:07
I can reproduce the problem, need to discuss with the rest of the team is this really a bug or a feature. I see this a bug because page is already closed and it is not needed in the catalog.

**Comment by aaltat** [comment] 2022-03-17 19:49
After reading more code, I am starting to think that current implementation might actually be correct. Even page is closed, it is still active page, in library internal state. In this case it would be strange to not report the active page in the catalog. Also because page is closed, it does not have title and this case we report it as `None`. 

But my opinion is not strong in the matter and I will reach rest of the team to confirm my assumption.

**Comment by aaltat** [comment] 2022-03-18 08:27
Did discuss with the rest of the team. How it currently works is wrong and it should be fixed. Will read Playwright API docs and see can we register a event listener and clean up the catalog automatically.

**Comment by jchenuw** [comment] 2022-04-12 18:25
As you mentioned, we can add an event listener and the Playwright Page object has an **on('close')** listener. So, I am wondering if we can change `_newPage` in playwright-state.ts to receive the `IndexedContent` for automatic cleanup:

```
async function _newPage(context: IndexedContext, page: Page | undefined = undefined): Promise<IndexedPage> {
    const newPage = ((page === undefined) ? await context.c.newPage() : page);
    const contextPage = indexedPage(newPage);
    newPage.on('close', () => {
        const oldPageStackLength = context.pageStack.length
        const filteredPageStack = context.pageStack.filter((page: IndexedPage) => page.p != contextPage.p)

        if(oldPageStackLength != filteredPageStack.length) {
            context.pageStack = filteredPageStack
            logger.info("Removed " + contextPage.id + " from " + context.id + " page stack")
        }
    });
    return contextPage;
}
```

Then for `_newBrowserContext` and `newPage`, which handles creating an `IndexedPage`, we can delegate like so
```
c.c.on('page', async (page) => {
     c.pageStack.unshift(await _newPage(c, page));
});
```
```
const page = await _newPage(context.context);
```

If we close the page manually,
```
export async function closePage(openBrowsers: PlaywrightState): Promise<Response.PageReportResponse> {
    const activeBrowser = openBrowsers.getActiveBrowser();
    const closedPage = activeBrowser.popPage();
    if (!closedPage) throw new Error('No open page');
    await closedPage.p.close();
    return pageReportResponse('Successfully closed Page', closedPage);
}
```

I'm not sure how the **on('close')** listener can remove the page more cleanly from the `pageStack`, since the page can be in any position when it is closed through non-explicit means.

**Comment by aaltat** [comment] 2022-04-13 11:38
Your idea looks solid one and by a quick look do not see why it could not work. Please continue your work.

**Comment by jchenuw** [comment] 2022-04-14 17:42
I am also wondering why the decision was to maintain a `pageStack` instead of using the Playwright `BrowserContext`'s `pages()` method.

**Comment by aaltat** [comment] 2022-04-14 17:46
Most likely it didn't not exist when that feature didn't exist in Playwright side when library was built. But it can be always changed.

**Closed** 2022-04-18 14:11 UTC
Labels: bug, priority: medium
