### ISSUE TITLE
Browser.SessionStorage Set Item does not accept value with special characters

### ISSUE THREAD

**Issue by GavinRodgers-EN0055** [MarketSquare/robotframework-browser#2248] opened 2022-08-17 15:07 UTC
**Describe the bug**
Trying to set an item into session storage that is a JSON blob but of type string e.g.
`{"json-string":{"key1":"value1","key2":"value2","key3":"value3","key4":"value4",}}`
But I get the following error:
```
Error: page.evaluate: SyntaxError: missing ) after argument list
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:178:30)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
```
However when i add the string `test-text` it works as expected
**To Reproduce**
This is the code I am currently using to remove and replace the sessionstorage key named policyholder.
```
    SessionStorage Remove Item    policyholder
    SessionStorage Get Item    policyholder  == ${NONE}
    ***Code to format the JSON string to be set***
    SessionStorage Set Item    policyholder    ({"test-text"}:test-text)
```
1. Go to any website
2. Attempt to set sessionStorage item the the above JSON string

**Expected behavior**
The string, with special characters should be added as a value for the session storage item

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 104
 (Above is ran on BrowserStack)

**Additional context**
Browser Library - 13.1.0

**Comment by aaltat** [comment] 2022-08-20 16:01
The `({"test-text"}:test-text)` is not valid json and I would assume that failure is caused by this reason. In practice keyword is really simple, we execute JavaScript: `window.sessionStorage.setItem("{key}", "{value}")`, where `{key}` and `{value}` are replaced with keyword arguments. You can execute same thing from browser console, example Firefox and try how you should format the command correctly. 

But because everything should work correctly from library point of view, I am going to close the issue.

**Closed by aaltat** 2022-08-20 16:01 UTC
