### ISSUE TITLE
17.5.2: After closing and opening a new browser, list index out of range

### ISSUE THREAD

**Issue by lasselindqvist** [MarketSquare/robotframework-browser#3818] opened 2024-10-04 10:26 UTC
Trying to update from 17.2.0 to 17.5.2 automatically in one of our existing test cases we get:

```

*** Settings ***

Library     Browser

*** Test Cases ***

Test
    Browser.New Browser  firefox  headless=False
    Browser.Close Browser
    Browser.New Browser  firefox  headless=False
    Browser.New Context  ignoreHTTPSErrors=True
    Browser.Set Browser Timeout  20 seconds
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/Browser/browser.py", line 1085, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/robotlibcore.py", line 173, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
  File "/usr/local/lib/python3.10/dist-packages/Browser/keywords/browser_control.py", line 313, in set_browser_timeout
    self.timeout_stack.set(self.convert_timeout(timeout), scope)
  File "/usr/local/lib/python3.10/dist-packages/Browser/utils/settings_stack.py", line 54, in set
    self._stack[self._last_id] = ScopedSetting(Scope.Suite, setting)
  File "/usr/local/lib/python3.10/dist-packages/Browser/utils/settings_stack.py", line 31, in _last_id
    return list(self._stack.keys())[-1]
IndexError: list index out of range
```

https://github.com/MarketSquare/robotframework-browser/blob/3444aaef92569341ed5c3d84ea6fddb515c194d0/Browser/utils/settings_stack.py#L31

**Comment by aaltat** [comment] 2024-10-05 08:58
@allcontributors please add @lasselindqvist for bug

**Comment by Snooz82** [comment] 2024-10-06 16:38
@lasselindqvist 
I am pretty sure that you can not reproduce it with this test case.
And i am pretty sure that it is #3208

This has been fixed in 18.0.0 

The 17.5.2 is a year old! Why aren't you updating to the newest version?

**Comment by lasselindqvist** [comment] 2024-10-06 17:04
I would want to update, but https://github.com/MarketSquare/robotframework-browser/issues/3286 is a blocker since downloading files does not work on that.

**Comment by Snooz82** [comment] 2024-10-06 18:29
i hope by making the browser options optional that #3286 is solved.
I could not reproduce that.
Would be cool, if you could deliver a reproduction for that issue.

I close this one, because that is fixed.

**Closed by Snooz82** 2024-10-06 18:29 UTC
Labels: bug, priority: high, closeable?
