### ISSUE TITLE
Wait For Condition only honors a timeout bigger than Browser timeout

### ISSUE THREAD

**Issue by tomppa65** [MarketSquare/robotframework-browser#3950] opened 2024-12-09 12:32 UTC
**Describe the bug**
In https://github.com/MarketSquare/robotframework-browser/issues/3036 you modified the timeout processing so that an assertion timeout that is bigger than the library timeout is stored as the current timeout. Why? What if I want to fail my Wait For Condition sooner than the library timeout? Wouldn't it be better to just honor a local override of timeout if it is **different** from the library timeout?

**Expected behavior**
If my library timeout is by default 15 s and my test executes
`Wait For Condition    Text    <selector>    validate    len(value) > 2    timeout=5s`
the Browser library waits for 15 seconds before failing the Text getting, instead of five seconds as I expected.

**Screenshots**
<img width="953" alt="image" src="https://github.com/user-attachments/assets/6033122a-e588-4006-a1f3-eb89396eba9d">

**Comment by aaltat** [comment] 2024-12-09 21:23
Looks strange, I need discuss with the team why it was done like that. 

@allcontributors please add @tomppa65 for bugs.

**Comment by Snooz82** [comment] 2024-12-10 07:30
@tomppa65 
This is by design.
I improved the docs for the next release.

The browser timeout will be used to find the element first.
After that the waiting happens.

We could change that, but that would be a backwards incompatibility.

@aaltat What do you think?

**Comment by aaltat** [comment] 2024-12-11 20:04
Ah, I did misunderstood the original problem. I think current implementation is correct. 

Or is this regression?

**Comment by aaltat** [comment] 2024-12-16 12:47
Closing

**Closed by aaltat** 2024-12-16 12:47 UTC
