### ISSUE TITLE
Problem with Get Element, cascaded selectors and/or *-prefix in Browser version 10+

### ISSUE THREAD

**Issue by Kahiis** [MarketSquare/robotframework-browser#1578] opened 2021-11-30 16:26 UTC
**Describe the bug**
Prior to Browser library version 10, I used `Get Element` and the `*` character to capture the parent element containing given text (Practically identically like explained under the Cascaded selector syntax in the keyword documentation). I would later on pass that element around and use it as a selector to extract and assert information. This interaction worked in version 9.0.2, but in later versions it seems that `Get Element` doesn't resolve to the element anymore, resulting in the future use of the retrieved variable not working as previously intended.

**To Reproduce**
I've managed to reproduce the behaviour with the following page and test case. Pardon the simplicity.

page.html
```
<ul>
    <li>
        <button>
            <h3>namegoeshere</h3>
            <p>42</p>
            <p>24</p>
        </button>
    </li>
    <li>
        <button>
            <h3>anothernamegoeshere</h3>
            <p>foo</p>
            <p>bar</p>
        </button>
    </li>
</ul>
```
test.robot
```
*** Settings ***
Library   Browser

*** Test Cases ***
Get Element problem test
    New Page       ${EXECDIR}\\page.html
    # note the * -character. Again, see the Cascaded selector syntax in the keyword documentation as well.
    ${button_element}=    Get Element    *xpath=//button >> text="namegoeshere"
    ${val}=    Get Text    ${button_element} >> xpath=//p[1]
    should be equal    ${val}    42
```
**Expected behavior**
the `${button_element}` variable should get resolved to the first `button` element in the example page, containing the `h3` element with the text `namegoeshere` and the `p` elements. Then that variable should be used as selector in the next line, retrieving the text `42` in the `p` element. The following `should be equal` assertion in the test case should then succeed. I've confirmed this to work with Browser library version 9.0.2.

However in Browser library version 10+ (in this case 10.1.0) the `Get Text` fails on a TimeoutError.
```
TimeoutError: locator.elementHandle: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for selector "*xpath=//button >> text="namegoeshere" >> xpath=//p[1]"
============================================================
```
This issue is present in all 3 browser engines, regardless of headless mode. Python version 3.10, Node version 14.18.1.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser confirmed on all browser engines
 - Version 21H1
 
 **Additional context**
Was the desired behavior I've described even intended in the first place🤔

**Comment by aaltat** [comment] 2021-11-30 16:59
@allcontributors please add @Kahiis for bugs

**Comment by aaltat** [comment] 2021-12-06 18:30
Interesting. When I install 9.0.2 and do this
```

**Comment by Kahiis** [comment] 2021-12-15 15:37
Sorry for necroing an old resolved issue, but I'm not 100% sure that issue has been understood correctly. I'll try to explain my thoughts better here. This regression indeed seems to be the result of swapping from elementhandles to locators, but I would still argue that the interaction is desirable.

The following line was indeed never intended to work in the first place.
```
    Get Text    *xpath=//button >> text="namegoeshere" >> xpath=//p[1]  ==    42
```
I'm not sure if my initial description of the intended behavior was a bit confusing, so I'm going to try and explain it again.

Prior to the switch from elementhandles to locators in v10+, the following line would resolve and cache the DOM-element of the `button` element in my example. 
```
    ${button_element}=    Get Element    *xpath=//button >> text="namegoeshere"
```
Note the `*` prefix on the xpath-selector, and see the [intermediate matches-section here](https://playwright.dev/docs/selectors/). The variable ${button_element} should get resolved to the `button` element, instead of the last matching `h3` element.
```
<ul>
    <li>
        <button>      <--- ${button_element}
            <h3>namegoeshere</h3>    <--- ! ${button_element} should have no relation to this element whatsoever at this point !
            <p>42</p>
            <p>24</p>
        </button>
    </li>
    <li>
        <button>
            <h3>anothernamegoeshere</h3>
            <p>foo</p>
            <p>bar</p>
        </button>
    </li>
</ul>
```
And as the results from `Get Element` can be used as selectors in future keywords (as per the [Browser documentation](https://marketsquare.github.io/robotframework-browser/Browser.html#Get%20Element) **(this bit still refers to element handles btw)**, [Playwright elementhandle](https://playwright.dev/docs/api/class-elementhandle) documentation doesn't mention this explicitly to my knowledge), then the following lines _should_ point to the first `p` element within the button as demonstrated and assertion should succeed.
```
    ${val}=    Get Text    ${button_element} >> xpath=//p[1]
    should be equal    ${val}    42
```
Or
```
    Get Text    ${button_element} >> xpath=//p[1]  ==    42
```
```
<ul>
    <li>
        <button>
            <h3>namegoeshere</h3>
            <p>42</p>    <---- ${val} , or ${button_element} >> xpath=//p[1]
            <p>24</p>
        </button>
    </li>
    <li>
        <button>
            <h3>anothernamegoeshere</h3>
            <p>foo</p>
            <p>bar</p>
        </button>
    </li>
</ul>
```
But alas, this interaction doesn't work anymore. To my understanding it's because `Get Element` doesn't cache elementhandles anymore -> ${button_element} is not resolved to the `button` DOM-element = the assertion receives a mangled cascaded selector instead. This behavior was massively useful in my use scenarios, since I didn't need to escape any special characters with the text-engine. In my case I have a bit of an edge case scenario with my text(s) containing both `'` and `"` characters, which are a massive pain to escape using xpath. However, I've since managed to find an alternative solution for my use case.
```
Get text    *xpath=//p[1] >> xpath=//../.. >> text=namegoeshere    ==    42
```
Not quite as elegant as my previous implementation but it works. For now. Please don't take this away from me :(


At this point I would like to present my argument against the caching of Locators instead of elementhandles for `Get Element`. If I've understood the playwright documentation correctly, the main difference between elementhandles and locators is that elementhandles resolve the DOM-element the moment they're created and locators just contain the logic to resolve the desired element much like a pointer, right?

If so, with the current implementation, what use does `Get Element` even have? If it doesn't resolve to the DOM-element as per the selector, I don't see it any more useful than assigning the selector/'element' to a variable using `Set Variable` etc. As I've been trying to describe, `Get Element` was massive useful for getting intermediate matches. Another use for elementhandle 'Get Element' would be cases where between subsequent views an element would share selector(poor design, but it happens), and between views I would like to assure that the previous element does indeed disappear, something along the lines of this:
```
Example
    Wait For Elements State    foobar
    ${elem_with_duplicate_selector}=    Get Element    foobar
    ... initiate page transition
    Wait For Elements State    ${elem_with_duplicate_selector}    detached
```
I'm not versed well enough in playwright or the current Browser implementations to know if both elementhandles and locators could both coexist, nor how. But I sure would like to have the option. Thoughts?

**Comment by aaltat** [comment] 2021-12-20 20:17
I might have an idea what causes this, but I need to do some experiments with Playwright.

**Comment by aaltat** [comment] 2022-02-04 22:04
I did some research and I am pretty sure that fault lies in the Playwright side: https://github.com/microsoft/playwright/issues/11522 

I made simple example that reproduces the problem in Playwright side. Unfortunately the proposed workaround is not suitable for us, because Browser library does not yet support `hasText` in locators.

**Comment by Kahiis** [comment] 2022-02-05 11:23
Thanks a ton @aaltat for doing the research and getting back to this issue! Let's hope a fix is coming to the playwright side of things in the future.

**Comment by aaltat** [comment] 2023-08-12 10:43
Closing, because problem is in PW side.

**Closed by aaltat** 2023-08-12 10:43 UTC
Labels: HEL, closeable?
