### ISSUE TITLE
"failed to connect to all addresses" error in "close" method

### ISSUE THREAD

**Issue by frankyqa** [MarketSquare/robotframework-browser#463] opened 2020-10-29 20:02 UTC
**Describe the bug**
Referring to https://github.com/MarketSquare/robotframework-browser/pull/423

Unfortunately, this fix did not solve my problem. It seems, my error is not of type "ConnectionError". I could not figure out which type it is though. Still getting this in the log file:

![image](https://user-images.githubusercontent.com/71194310/97624040-d0420880-1a26-11eb-91bd-1a46fe661bf0.png)

I formerly thought this is not that big of a problem since the test case passes. But as soon as I execute 2 test cases, the second one fails with `Playwright process has been terminated with code 1`

**To Reproduce**
1. Set up testcase with browser library and DataDriver structure
2. Execute test case
3. Check log file

**Expected behavior**
No error is displayed. Testcase passes.

**Screenshots**
Testcase file:

```
*** Settings ***
Test Template    Starting a browser with a page

Library          DataDriver    ${CURDIR}/MapTestDataToTestcaseMatrix.csv
Library          Browser


*** Test Cases ***
Starting Sample Testcase
    ${CURDIR}/${arg_testdata_file_name}    ${arg_tags}    ${arg_issue_key}


*** Keywords ***
Starting a browser with a page
    New Browser    chromium    headless=false
    New Context    viewport={'width': 1920, 'height': 1080}
    New Page       https://marketsquare.github.io/robotframework-browser/Browser.html
    Get Title      ==    Browser
```

DataDriver CSV file:
```
*** Test Cases ***;${arg_testdata_file_name};${arg_tags};${arg_issue_key};[Documentation]
Starting Sample Testcase;TestCaseData.csv;release;1;
```

Testcase data CSV file:
`Testdata1;test
`

**Desktop:**
OS: Windows 10
Browser: Google Chrome 86
Robot Framework: 3.2.2
Browser Library: 1.7.0
DataDriver: 1.0.0

**Comment by aaltat** [comment] 2020-10-29 21:26
Could you enable the [enable_playwright_debug](https://marketsquare.github.io/robotframework-browser/Browser.html#Importing) form library import and share the debug file form the output folder? 

How do you run the test case?

**Comment by frankyqa** [comment] 2020-10-30 06:49
I start the test case out of my editor (RED in my case). Starting via command line gets me the same results. So no CI etc. involved.

**Playwright log:**
```
{"level":30,"time":"2020-10-30T06:34:26.318Z","pid":1788,"hostname":"myhost","msg":"Listening on 64066"}
2020-10-30T06:34:26.804Z pw:api => browserType.launch started
2020-10-30T06:34:28.187Z pw:api <= browserType.launch succeeded
2020-10-30T06:34:28.201Z pw:api => browser.newContext started
2020-10-30T06:34:28.224Z pw:api <= browser.newContext succeeded
2020-10-30T06:34:28.225Z pw:api => browserContext.addInitScript started
2020-10-30T06:34:28.226Z pw:api <= browserContext.addInitScript succeeded
{"level":30,"time":"2020-10-30T06:34:28.226Z","pid":1788,"hostname":"myhost","msg":"Changed active context"}
2020-10-30T06:34:28.241Z pw:api => browserContext.newPage started
2020-10-30T06:34:28.553Z pw:api <= browserContext.newPage succeeded
{"level":30,"time":"2020-10-30T06:34:28.553Z","pid":1788,"hostname":"myhost","msg":"Changed active page"}
2020-10-30T06:34:28.554Z pw:api => page.goto started
2020-10-30T06:34:28.554Z pw:api navigating to "https://marketsquare.github.io/robotframework-browser/Browser.html", waiting until "load"
2020-10-30T06:34:29.588Z pw:api   navigated to "https://marketsquare.github.io/robotframework-browser/Browser.html"
2020-10-30T06:34:29.886Z pw:api   "domcontentloaded" event fired
2020-10-30T06:34:30.461Z pw:api   "load" event fired
2020-10-30T06:34:30.462Z pw:api <= page.goto succeeded
2020-10-30T06:34:30.470Z pw:api => page.title started
2020-10-30T06:34:30.480Z pw:api <= page.title succeeded
2020-10-30T06:34:30.488Z pw:api => page.title started
2020-10-30T06:34:30.490Z pw:api <= page.title succeeded
{"level":30,"time":"2020-10-30T06:34:30.495Z","pid":1788,"hostname":"myhost","msg":"Changed active context"}
{"level":30,"time":"2020-10-30T06:34:30.496Z","pid":1788,"hostname":"myhost","msg":"Changing current active page"}
{"level":30,"time":"2020-10-30T06:34:30.496Z","pid":1788,"hostname":"myhost","msg":"Changed active page"}
2020-10-30T06:34:30.496Z pw:api => page.bringToFront started
2020-10-30T06:34:30.498Z pw:api <= page.bringToFront succeeded
2020-10-30T06:34:30.504Z pw:api => page.title started
2020-10-30T06:34:30.506Z pw:api <= page.title succeeded
{"level":30,"time":"2020-10-30T06:34:30.527Z","pid":1788,"hostname":"myhost","msg":"Changed active context"}
{"level":30,"time":"2020-10-30T06:34:30.528Z","pid":1788,"hostname":"myhost","msg":"Changing current active page"}
{"level":30,"time":"2020-10-30T06:34:30.528Z","pid":1788,"hostname":"myhost","msg":"Changed active page"}
2020-10-30T06:34:30.528Z pw:api => page.bringToFront started
2020-10-30T06:34:30.529Z pw:api <= page.bringToFront succeeded
2020-10-30T06:34:30.533Z pw:api => browserContext.close started
2020-10-30T06:34:30.629Z pw:api <= browserContext.close succeeded
2020-10-30T06:34:30.647Z pw:api => browser.close started
2020-10-30T06:34:31.058Z pw:api <= browser.close succeeded

```

**Comment by aaltat** [comment] 2020-10-30 09:22
So I would assume that test is executed by using `robot` and not by using example `pabot`?

**Comment by frankyqa** [comment] 2020-10-30 10:20
Yes, just `robot`. No `pabot`.

**Comment by aaltat** [comment] 2020-11-17 07:28
I investigated the problem and issue is caused because Robot Framework calls twice the `close` [listener API](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-interface-methods). But it should not cause anymore tests to fail, because we log a warning, since 1.6.0 release. 

Although the issue is outside of the Browser library, lets keep the issue open so that we remember to report the problem in upstream (either this is caused by something what DataDriver does, or this is a bug in RF core).

**Comment by aaltat** [comment] 2020-11-22 22:04
I think this is problem with Robot Framework. I have small PoC, without DataDriver or Browser library, which causes RF to call the `_close` listener API two times. More details in https://github.com/robotframework/robotframework/issues/3772 But because this looks like RF problem, there is not much what we can do in Browser library side to fix it.

**Comment by frankyqa** [comment] 2020-11-23 08:13
thank you for all your effort. I really appreciate.

**Comment by aaltat** [comment] 2020-11-28 23:58
This is bug in the RF and it's fixed in the next RF 4 release. There is also a workaround available, but that requires changing code in the DataDriver side. See more details in robotframework/robotframework#3772

In any case there is not anything we could do it to fix this problem in the Browser library side. Users should use the latest RF from GitHub repository or ask/modify DataDriver to contain a keyword.

**Comment by aaltat** [comment] 2020-12-01 13:29
Did forget to close and marked as invalid because bug was in RF core side.

**Closed by aaltat** 2020-12-01 13:29 UTC
Labels: invalid
