### ISSUE TITLE
Second time the keyword "New Browser" is used no new browser is opened 

### ISSUE THREAD

**Issue by BjornAhmark** [MarketSquare/robotframework-browser#2821] opened 2023-05-25 09:48 UTC
**Describe the bug**
Second time the keyword "New Browser" is used no new browser window is opened instead a new tab is added to the first opened browser

**To Reproduce**
1. Create a test script where the keyword "New Browser" is used twice
2. Run the test script
3. The second time the "New Browser" keyword is called a second browser window should be opened, but currently a new tab is opened in the first browser window

**Expected behavior**
The second time the "New Browser" keyword is called a second browser window should be opened

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.3.1
 - Browser: Chromiun
 - Version: 113.0.5672.53

**Additional context**
Works as expected in robotframework-browser version 15.2.0, but not for version 16.0.0 to 16.1.0

**Comment by BjornAhmark** [comment] 2023-05-25 11:53
This bug is maybe caused by this bug: https://github.com/MarketSquare/robotframework-browser/issues/2669

**Comment by aaltat** [comment] 2023-05-26 21:45
If your test looks like this:
```
Example 1
    New Browser    chromium    False
    New Page    https://marketsquare.github.io/robotframework-browser/Browser.html#New%20Browser
    New Browser    chromium    False
    New Page    https://github.com/MarketSquare/robotframework-browser/issues/2821
```
Then Browser library is working as expected, please see [New Browser](https://marketsquare.github.io/robotframework-browser/Browser.html#New%20Browser)  `reuse_existing` argument and it is by default set as true. 

But if you test looks like this: 
```
Example 2
    New Browser    chromium    False    reuse_existing=False
    New Page    https://marketsquare.github.io/robotframework-browser/Browser.html#New%20Browser
    New Browser    chromium    False    reuse_existing=False
    New Page    https://github.com/MarketSquare/robotframework-browser/issues/2821
```
Then pages are opened as you expect. 

I am closing this issue, because most likely this is caused by the `reuse_existing` argument being true. If this is not that, please, please send us a update.

**Closed by aaltat** 2023-05-26 21:45 UTC

**Comment by aaltat** [comment] 2023-05-26 21:47
@allcontributors please add @BjornAhmark for bugs.
