### ISSUE TITLE
"Select Options By" accepts faulty options

### ISSUE THREAD

**Issue by anton264** [MarketSquare/robotframework-browser#609] opened 2020-12-22 13:32 UTC
**Describe the bug**

Using the following html
```
<label for="cars">Choose a car:</label>

<select name="cars" id="cars">
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>
```
And this robot code:
```
*** Settings ***
Library        Browser

*** Test Cases ***

List
    New Browser        headless=False   
    New Page    file:///file.html
    Get Property    id=cars    length    ==    ${4}
    Select Options By    id=cars    text        Volvo    Saab    Lada    Audi
```
The keyword will not fail due to option "Lada" not existing, as long as one valid option is provided the keyword will go through

**Expected behavior**
Keyword should fail when invalid argument is present.

**Comment by aaltat** [comment] 2020-12-22 14:14
@all-contributors please add @anton264 for userTesting

**Comment by aaltat** [comment] 2020-12-22 14:37
That is the way [Playwright works](https://playwright.dev/docs/api/class-page/#pageselectoptionselector-values-options), but playwright also returns (which we do not currently use) list of selected options. We could add some logic to verify that correct options are selected. At minimum we should document the feature.

**Comment by Snooz82** [comment] 2020-12-22 14:38
Hi @anton264 ,

Actually this keyword works so, that it checks all matches. It does not fail. If you want a fail, if the required options are not found, you should use `Get Selected Options` afterwards.

this is by design and how the underlying Playwright works.

I would not change that behavior by now.

cheers

**Comment by anton264** [comment] 2020-12-22 15:58
How about an optional argument that checks the length of the return array from playwright and checks if it matches the length of `values`? It could be default off so the current behaviour is kept but strict checking is possible.

**Comment by Snooz82** [comment] 2020-12-22 22:38
@anton264 

i will implement a keyword `Get Options`

you can use it to assert the length like this
```
Get Options     select    text    validate    len(value) == 6
```

Or the values like this:
```
Get Options    select    text    ==    Minigolf    I5    Keines    Rassant Family    Rolo    Rassant
# or
Get Options    select    text    contains    Minigolf
```


I think that one is missing at the moment. Only asserting the selected ones does not really makes sense... 
It was easy to implement.
Now Docs and Tests ;-)

**Comment by Snooz82** [comment] 2020-12-22 22:39
Or should it be 
`Get Select List Options` ?

**Comment by anton264** [comment] 2020-12-23 06:41
I think that `Get Select List Options` is a better option since `Get Options` might confuse people to think of chrome options or other types of options. Otherwise I like your suggestion @Snooz82 it would also resolve #608

**Comment by aaltat** [comment] 2021-12-04 23:41
With new version of Playwright we could return list of option values that have been successfully selected. I think that would allow you to verify that keyword has worked correctly.

**Comment by aaltat** [comment] 2021-12-05 21:59
Because this issue is long it is hard to see what actually was changed. I created #1594 and will close this one. If there need for new enhancements, please submit new issue.

**Closed by aaltat** 2021-12-05 21:59 UTC
Labels: bug, priority: high
