### ISSUE TITLE
Connection error in log file when using DataDriver with Browser library

### ISSUE THREAD

**Issue by frankyqa** [MarketSquare/robotframework-browser#422] opened 2020-10-17 20:13 UTC
**Describe the bug**
I get this error message in the log file when I use DataDriver along with Browser library:

`Error in library 'Browser': Calling method '_close' of listener 'Browser' failed: failed to connect to all addresses`

I did not get a stack trace because the error does not interfere with test execution (yet). It is just displayed in the log file. My browser lib version is 1.3.0 and my DataDriver version is 0.3.3.

**To Reproduce**
1. Set up test case with DataDriver
2. Execute "New browser" example von keyword documentation
3. Check log file

**Expected behavior**
No error is displayed. Testcase passes.

**Screenshots**
![image](https://user-images.githubusercontent.com/71194310/96352509-03e66f80-10c4-11eb-918a-a1820072326b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 86

**Comment by aaltat** [comment] 2020-10-17 20:33
I think this is a duplicate of #380

**Closed** 2020-10-17 21:49 UTC
