### ISSUE TITLE
Trying to delete video record directory in suite teardown fails when the video record directory does not exist

### ISSUE THREAD

**Issue by ssallmen-pro** [MarketSquare/robotframework-browser#2206] opened 2022-07-25 14:25 UTC
**Describe the bug**
I would like to delete the recorded videos in the suite teardown if the suite passes. And, I would specifically like to use the directory path stored to the dictionary I have given for Browser.New Context as recordVideo argument as the path to be deleted. But, that does not succeed, if the directory was empty before calling Browser.New Context with the recordVideo dictionary.

**To Reproduce**
This is a very much simplified version of an example test suite with which the bug can be replicated:
```
*** Settings ***
Library    Browser
Library    OperatingSystem
Suite Teardown    Delete Dirs If Suite Passed

*** Variables ***
${VIDEO_DIR}    ${OUTPUT_DIR}/video/${SUITE_NAME}
&{RECORD_VIDEO}    dir=${VIDEO_DIR}
${FOO_DIR}    ${OUTPUT_DIR}/foo/${SUITE_NAME}
&{FOO}    dir=${FOO_DIR}

*** Test Cases ***
Open Google
    Browser.New Browser    headless=False
    Browser.New Context    recordVideo=${RECORD_VIDEO}
    # OperatingSystem.Create Directory    ${RECORD_VIDEO.dir}    # This would fail
    OperatingSystem.Create Directory    ${VIDEO_DIR}    # But this does not fail
    Browser.New Page    https://www.google.com/

# Create File
#     Create File    ${FOO.dir}/bar.txt    content=foobar

*** Keywords ***
Delete Dirs If Suite Passed
    IF    '${SUITE_STATUS}' == 'PASS'
        Remove Directory    ${FOO.dir}    recursive=True    # This will pass always, independent of existence of the directory.
        # Remove Directory    ${VIDEO_DIR}    recursive=True    # Also this would pass always.
        Remove Directory    ${RECORD_VIDEO.dir}    recursive=True    # But this will pass only if the directory to be removed existed before call to Browser.New Context -keyword.
    END
```

The `Remove Directory  ${RECORD_VIDEO.dir}  recursive=True` call in suite teardown keyword fails when the directory did not exist before `Browser.New Context` was called. If it did exist (for example when the teardown had last time failed) before the `Browser.New Context` call, it will succeed. That makes the above test suite execution fail on every second run if nothing else changes.

**Specifically it seems to have something to do with the usage of `${RECORD_VIDEO.dir}` in the above example. If I use the variable (`${VIDEO_DIR}`) that I have used to construct the dictionary for the directory removal, it would be ok.**

The failure does not tell very much at all (loglevel was TRACE):
![image](https://user-images.githubusercontent.com/98014506/180798136-d7706cbb-12bb-4541-8f57-380237dbabec.png)

Note that also the creation of the directory using `${RECORD_VIDEO.dir}` after calling `Browser.New Context  recordVideo=${RECORD_VIDEO}` would fail. The above suite has a commented out line for that too.

**Expected behavior**
The teardown would succeed every time, and delete the video directory successfully when the test passes.

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome 103.0.5060.134
 - RF Browser Library version 13.3.0

**Comment by aaltat** [comment] 2022-07-25 20:01
I don't understand why invalid usage of OperatingSystem library is bug in this library, closing the issue.

**Closed by aaltat** 2022-07-25 20:01 UTC

**Comment by ssallmen-pro** [comment] 2022-07-26 07:21
@aaltat It is not actually invalid usage of OperatingSystem library, or how do you think so?
It is totally acceptable to try to delete a non-existing folder using Remove Directory, as you see that when using a simple variable, or even direct path as string, to delete the same path, is successful. This error does NOT happen, if I don't call `Browser.New Context` and give that dictionary for it as recordVideo.

**Comment by aaltat** [comment] 2022-07-26 08:55
Did you look at the error on the OperatingSystem library?

**Comment by ssallmen-pro** [comment] 2022-07-26 09:02
Yes I did, but it does not make any sense. I am giving one positional argument and one named argument for Remove Directory, and it complains that "replace() takes 2 positional arguments but 3 were given". I am giving exactly the same arguments also in case the directory exists before calling New Context. I am not changing the test case and it fails every second time (when the dir does not exist before calling New Context) and passes every every second time (when the dir exists before calling New Context). Only calling New Context has something to do with this.

**Comment by ssallmen-pro** [comment] 2022-07-26 09:09
In the error description I have offered you the simple test suite, with which you can easily replicate the issue and see yourself that only calling New Context and existing/non-existing video directory has something to do with this. Would you be so kind that you would try that out yourself. Just copy the test suite in description to some file, or I can attach it for you here, and run it twice.
[browser_video.txt](https://github.com/MarketSquare/robotframework-browser/files/9188345/browser_video.txt)

**Comment by aaltat** [comment] 2022-07-26 09:11
Because Browser and OperatingSystem libraries are independent and do not know anything about each other,  therefore  I don't understand why failure in OperatingSystem library is issue in Browser library.  This issue remains closed 

If you want further support ask from the community.

**Comment by ssallmen-pro** [comment] 2022-07-26 09:11
Meanwhile, I am trying to find where that issues really resides. It can of course be also in OperatingSystem library but I need to know first what happens in Browser library for that path in dir-key of the dictionary given as recordVideo argument for New Context.

**Comment by ssallmen-pro** [comment] 2022-07-26 09:13
Ok Tatu. Let it be like that. I just tried to help out others who would like to delete the videos of passed suite execution, as this would probably be the best way to do that, but I see that you are not co-operative.

**Comment by aaltat** [comment] 2022-07-26 10:02
The bug is in the OperatingSystem library. The error says that OperatingSystem library tries to execute some Python function and that function is expecting 2 positional arguments but 3 where given by the OperatingSystem library.  Therefore this is bug in the OperatingSystem library. 


You are just being lucky that the problem can be reproduced with Browser library in reliable manner.

**Comment by ssallmen-pro** [comment] 2022-07-27 15:50
Just to summarize for possible other persons reading this closed bug report. The issue was caused by Browser library's `New Context` keyword mutating the dir-key value in the dictionary given for it as `recordVideo` argument. The value was originally set to be a string, but after calling `New Context` it is in some specific cases a Path-object, which is not accepted by the OperatingSystem library keywords, like `Remove Directory`. In some cases it is a string still.
There is a workaround for this, i.e. converting that Path-object (or string) to string using `Convert To String` before calling any keyword that accepts paths only as strings. There is also a new improvement issue created by me for this because that behavior should be consistent (always "returning" same type of object, string or Path) and that behavior should be documented in the keyword documentation: https://github.com/MarketSquare/robotframework-browser/issues/2215
