### ISSUE TITLE
Cannot set httpcredentials to new_persistent_context in python. 

### ISSUE THREAD

**Issue by gitkatsi** [MarketSquare/robotframework-browser#2835] opened 2023-06-03 10:19 UTC
**Describe the bug**
Cannot set httpcredentials to new_persistent_context in python. 

**To Reproduce**
```
pw = Browser()
pw.new_persistent_context(
    browser=SupportedBrowsers.chromium,
    headless=True,
    viewport={"width": 1920, "height": 1080},
    httpCredentials={'username':"admin", 'password':"admin"}
)
```
returns
`ValueError: Direct assignment of values or variables as 'httpCredentials' is not allowed. Use special variable syntax ($var instead of ${var}) to prevent variable values from being spoiled.`

**Expected behavior**
To create the browser and proceed with basic authentication, according to python example 
https://robotframework-browser.org/#examples -->testing in python.

**Additional context**

**Comment by aaltat** [comment] 2023-06-03 12:15
Duplicate of #2754

**Closed by aaltat** 2023-06-03 12:15 UTC
