### ISSUE TITLE
Chrome browser is not closing immediately and takes 30 seconds to close in non-headless mode

### ISSUE THREAD

**Issue by Sathish787** [MarketSquare/robotframework-browser#2284] opened 2022-09-06 16:51 UTC
After executing all tests in the suite in non-headless mode, chrome browser takes 30 seconds to close and terminate the thread. Issue found only in non-headless mode and works correctly in headless mode which is it terminates immediately and doesn't hold the thread for 30 seconds. 

Works as expected in Chromium and Firefox.
I see this as long time existing bug and not fixed yet with this library.

Also, this happens only in windows 10.

Is there any solution available to fix this problem. 
Thanks in Advance.
Sathish

**Comment by aaltat** [comment] 2022-09-06 18:59
The Browser library doesn't know know how browsers are are opened, we just pass arguments to Playwright side. Also the API for closing browsers has only one method and browsers are closed similar regards how they are opened. Also because Chromium works correctly when run in headless mode, I would assume that problem relies somewhere in the lower levels,  most likely in the Chromium side. Therefore there is not anything that we could do in the Browser library level to fix the problem. 

I don't recall hearing this type of problems, but it doesn't mean that problem would not exist. Instead I would suggest you to ask in the community channels,  example in the slack.

Closing issue because because it's not a bug or feature requests for the library.

**Closed by aaltat** 2022-09-06 18:59 UTC
