### ISSUE TITLE
Linux: Browser is closed after promise to wait for upload fails with file not found

### ISSUE THREAD

**Issue by zastress** [MarketSquare/robotframework-browser#1821] opened 2022-03-01 09:20 UTC
**Describe the bug**
Creation of new context failes on Linux for a test suite if the previous test crashed because of an upload file promise not delivered (file not found error). Aparently the browser crashes or is closed after the "file not found" error is received.

**To Reproduce**
```
*** Settings ***
Library    Browser
Suite Setup    New Browser    firefox

*** Variables ***
&{BROWSER-DEFAULT-CAPABILITIES}     acceptDownloads=True    ignoreHTTPSErrors=True    viewport={'width': 1920, 'height': 1080}

*** Test Cases ***
Test1
    New Context    &{BROWSER-DEFAULT-CAPABILITIES}
    New Page    https://www.onlineconverter.com/mp4
    ${promise}      Promise To Upload File          ${CURDIR}/nofile
    Click                                           css=#file
    Wait For        ${promise}

Test2
    New Context    &{BROWSER-DEFAULT-CAPABILITIES}
    New Page    https://www.onlineconverter.com/mp4
    Wait For Elements State    css=#file
```

To reproduce, simply run `robot Test.robot`. It is clear that there is not file called `nofile` in the current directory and that is the scope of the test. Fail information: `Error: browser.newContext: Target page, context or browser has been closed`

**Expected behavior**
Test1 should fail and Test2 should continue normally

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser firefox

**Additional context**
Same test works as expected on Windows.

Playwright error log:
```
================= Original suppressed error =================
page.bringToFront: Target page, context or browser has been closed
    at BrowserState.activatePage (/home/validation/.local/lib/python3.8/site-packages/Browser/wrapper/index.js:7201:19)
    at _switchPage (/home/validation/.local/lib/python3.8/site-packages/Browser/wrapper/index.js:7328:24)
    at switchContext (/home/validation/.local/lib/python3.8/site-packages/Browser/wrapper/index.js:7400:11)
    at async PlaywrightServer.switchContext (/home/validation/.local/lib/python3.8/site-packages/Browser/wrapper/index.js:7654:24) {
  name: 'Error'
}
=============================================================
{"level":30,"time":"2022-03-01T09:19:17.793Z","pid":30778,"hostname":"Liviu-Validation","msg":"Start of node method getBrowserCatalog"}
{"level":30,"time":"2022-03-01T09:19:17.793Z","pid":30778,"hostname":"Liviu-Validation","msg":"End of node method getBrowserCatalog"}
{"level":30,"time":"2022-03-01T09:19:17.795Z","pid":30778,"hostname":"Liviu-Validation","msg":"Start of node method newContext"}
{"level":30,"time":"2022-03-01T09:19:17.795Z","pid":30778,"hostname":"Liviu-Validation","msg":"currentBrowser: [object Object]"}
{"level":30,"time":"2022-03-01T09:19:17.795Z","pid":30778,"hostname":"Liviu-Validation","msg":"Trace file: "}
{"level":30,"time":"2022-03-01T09:19:17.796Z","pid":30778,"hostname":"Liviu-Validation","msg":"Error of node method  newContext"}
================= Original suppressed error =================
browser.newContext: Target page, context or browser has been closed
    at async _newBrowserContext (/home/validation/.local/lib/python3.8/site-packages/Browser/wrapper/index.js:6988:19)
    at async newContext (/home/validation/.local/lib/python3.8/site-packages/Browser/wrapper/index.js:7291:19)
    at async PlaywrightServer.newContext (/home/validation/.local/lib/python3.8/site-packages/Browser/wrapper/index.js:7495:28) {
  name: 'Error'
}
=============================================================
{"level":30,"time":"2022-03-01T09:19:17.797Z","pid":30778,"hostname":"Liviu-Validation","msg":"Start of node method takeScreenshot"}
{"level":30,"time":"2022-03-01T09:19:17.798Z","pid":30778,"hostname":"Liviu-Validation","msg":"Error of node method  takeScreenshot"}
================= Original suppressed error =================
page.screenshot: Target page, context or browser has been closed
    at takeScreenshot (/home/validation/.local/lib/python3.8/site-packages/Browser/wrapper/index.js:6147:17)
    at PlaywrightServer.takeScreenshot (/home/validation/.local/lib/python3.8/site-packages/Browser/wrapper/index.js:7495:34)
    at handleUnary (/home/validation/.local/lib/python3.8/site-packages/Browser/wrapper/node_modules/@grpc/grpc-js/build/src/server.js:674:13) {
  name: 'Error'
}
```

**Comment by zastress** [comment] 2022-03-04 10:11
Seems the same thing happens when this error occurs: `waiting for event "filechooser"`

**Comment by aaltat** [comment] 2022-03-09 20:57
I can reproduce the problem also with Mac and Firefox. But the problem can not be reproduced with Chromium and the Firefox works correctly when headless=False. Therefore I think this is a problem with Firefox implementation or PW binding to Playwright. I think best option would be you to create example which reproduces the in PW side and report the problem for them.

**Comment by aaltat** [comment] 2022-04-08 19:03
Because bug is Firefox browser side and therefore on Playwright side, I am going to close this issue.

**Closed by aaltat** 2022-04-08 19:03 UTC
