### ISSUE TITLE
Kerberos authentication issue

### ISSUE THREAD

**Issue by aloene** [MarketSquare/robotframework-browser#3944] opened 2024-12-06 08:18 UTC
**Describe the bug**
Using Robot Framework + Browser + httpCredential will not work against Kerberos-secured web applications.

**To Reproduce**
1. Use latest Playwright container image (`playwright:v1.49.0`) with Kerberos libs/config for your Active Directory environment and latest RobotFramework/Browser libs.
2. Create a RobotFramework test to access an internal/Kerberos-secured application "https://app.mydomain.com" with headless Chromium and test home page rendering. This test will include :
  - New Browser, with or without args like this (both tested, with/without double-quotes, too) :
    `New Browser         chromium    headless=true          args=['--auth-negotiate-delegate-allowlist="*.mydomain.com"','--auth-server-allowlist="*.mydomain.com"']`
  - New Context (with test user httpCredential) like this:
    `New Context         baseURL=${url}   viewport={'width': 1920, 'height': 1080}     httpCredentials={'username': '$username', 'password': '$password'}    tracing=true`
3. Also tried (not sure it will be read...) : add a chromium Policy in `/etc/chromium/policies/managed/` like this
```json
{
  "AmbientAuthenticationInPrivateModesEnabled": 3,
  "AuthServerAllowlist": "*.mydomain.com",
  "AuthNegotiateDelegateAllowlist": "*.mydomain.com"
}
```
5. Execute test.
6. Test will fail when trying to validate page content as browser seems stuck after getting initial Negotiate/401. Browser network trace show this HTTP 401 response (OK as a 1st step only) and blank page (screenshot). Authentication will not happen.

**Expected behavior**
HTTP Request can be authenticated using SPNego/Kerberos protocol using provided credential.

**Screenshots**
(blank screenshot)
Network trace (part of response):
```json
"response": {
    // ...
    "headers": [
         // ...
          {
              "name": "www-authenticate",
              "value": "Negotiate"
          }
      ],
      "headersSize": 610,
      "httpVersion": "HTTP/1.1",
      "redirectURL": "",
     "status": 401,
     "statusText": "Unauthorized"
 }
```

**Desktop (please complete the following information):**
 - Linux container (Ubuntu 04.24-based, playwright:v1.49.0 image)
 - Chromium (from playwright:v1.49.0 image)

--
Is there any clear documentation on this ? Kerberos authentication is a very common use case and I could not find good doumentation on setting this up with RobotFramework/Browser ... I could find [this](https://github.com/microsoft/playwright/issues/1730) and [this](https://github.com/MarketSquare/robotframework-browser/issues/814)... it seems it should work... but not for me with RobotFramework/Browser lib at least.

**Comment by aaltat** [comment] 2024-12-08 20:26
`httpCredentials` will in practice do a HTPP Authentication,  https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication , which not the same thing as Kerberos auth that you looking for. HTPP Authentication comes out of the box from Playwright: https://playwright.dev/docs/api/class-browser#browser-new-context-option-http-credentials 

Unfortunately I do not have good idea how to do the Kerboros auth, because never needed to thinks such problem, but you could ask in one of our community channels https://robotframework.org/#community 

Closing this issue because feature works as designed.

**Closed by aaltat** 2024-12-08 20:26 UTC

**Comment by aloene** [comment] 2024-12-09 11:04
> `httpCredentials` will in practice do a HTPP Authentication, https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication , which not the same thing as Kerberos auth that you looking for. HTPP Authentication comes out of the box from Playwright: https://playwright.dev/docs/api/class-browser#browser-new-context-option-http-credentials
> 
> Unfortunately I do not have good idea how to do the Kerboros auth, because never needed to thinks such problem, but you could ask in one of our community channels https://robotframework.org/#community
> 
> Closing this issue because feature works as designed.

OK, thanks for the answer. I understand httpCredentials is for **Basic** HTTP Authentication only.
I managed to make it work by initializing a Kerberos ticket before running browser with args above (without double-quotes).

However, there is something surprising: this works well with current headless mode (shell) but this does not work with channel=chromium... (I get an net::ERR_HTTP_RESPONSE_CODE_FAILURE and a 401 (ok) in traces)
